from __future__ import annotations

from typing import Protocol, runtime_checkable

from promptgate.models import PromptConfig


@runtime_checkable
class StorageBackend(Protocol):
    def init(self) -> None: ...
    def upsert(self, prompt: PromptConfig) -> None: ...
    def get(self, prompt_id: str) -> PromptConfig | None: ...
    def delete(self, prompt_id: str) -> bool: ...
    def list_all(self) -> list[PromptConfig]: ...
    def search_fts(self, query: str, limit: int = 5) -> list[tuple[str, float]]: ...
